apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dispatch-pipeline-runs
  namespace: saritasa-test
spec:
  workspaces:
    - name: shared-workspace
      description: Workspace containing the scripts.
  params:
    - name: changed-components
      type: string
      description: Space-separated list of components that changed.
    - name: gitrevision
      type: string
      description: The git revision/sha to build.
    - name: gitrepositoryurl
      type: string
      description: The git repository URL.
    - name: action
      type: string
      description: Action to perform (build or deploy).
      default: "build"
  steps:
    - name: dispatch
      image: alpine/k8s:1.20.4
      env:
        - name: CHANGED_COMPONENTS
          value: $(params.changed-components)
        - name: ACTION
          value: $(params.action)
        - name: GITREVISION
          value: $(params.gitrevision)
        - name: GITREPOSITORYURL
          value: $(params.gitrepositoryurl)
      script: |
        sh $(workspaces.shared-workspace.path)/tekton-platform/scripts/dispatch-pipeline-runs.sh
