apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: saritasa-test
spec:
  workspaces:
    - name: output
      description: The workspace where the repository will be cloned.
  params:
    - name: url
      type: string
      description: Git repository URL.
    - name: revision
      type: string
      description: Git revision to checkout.
  steps:
    - name: clone
      image: alpine/git:v2.30.2
      script: |
        #!/bin/sh
        set -e
        # Clean workspace first
        rm -rf $(workspaces.output.path)/*
        rm -rf $(workspaces.output.path)/.* 2>/dev/null || true
        
        git clone $(params.url) $(workspaces.output.path)
        cd $(workspaces.output.path)
        git checkout $(params.revision) || {
          git fetch origin $(params.revision) && git checkout FETCH_HEAD
        }
