apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saritasa-test

labels:
  - pairs:
      app.kubernetes.io/name: tekton-platform
      app.kubernetes.io/instance: tekton-platform
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/component: infrastructure
      app.kubernetes.io/part-of: saritasa-devops-build-samples
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

resources:
  - base
  - pipelines
  - tasks
  - triggers
