apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: orchestrator-pipeline
  namespace: saritasa-test
spec:
  params:
    - name: gitrevision
      type: string
      description: The git revision/sha to build.
    - name: gitrepositoryurl
      type: string
      description: The git repository URL.
    - name: action
      type: string
      description: The action to perform (build or deploy).
      default: "build"
  workspaces:
    - name: shared-workspace
      description: The workspace where the repository is cloned and scripts are accessed.
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.gitrepositoryurl)
        - name: revision
          value: $(params.gitrevision)
    - name: check-concurrency
      runAfter:
        - git-clone
      taskRef:
        name: check-concurrency
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
    - name: detect-changes
      runAfter:
        - check-concurrency
      taskRef:
        name: detect-changes
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: gitrevision
          value: $(params.gitrevision)
        - name: gitrepositoryurl
          value: $(params.gitrepositoryurl)
    - name: dispatch-pipeline-runs
      runAfter:
        - detect-changes
      taskRef:
        name: dispatch-pipeline-runs
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: changed-components
          value: $(tasks.detect-changes.results.changed-components)
        - name: action
          value: $(params.action)
        - name: gitrevision
          value: $(params.gitrevision)
        - name: gitrepositoryurl
          value: $(params.gitrepositoryurl)
