apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: orchestrator-pipeline
  namespace: saritasa-test
spec:
  params:
    - name: gitrevision
      type: string
      description: The git revision/sha to build.
    - name: gitrepositoryurl
      type: string
      description: The git repository URL.
    - name: action
      type: string
      description: The action to perform (build or deploy).
      default: "build"
  workspaces:
    - name: source-workspace
      description: Shared workspace for cloning, change detection, and building.
  tasks:
    - name: check-concurrency
      taskRef:
        name: check-concurrency
      params:
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
    - name: git-clone
      runAfter:
        - check-concurrency
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: url
          value: "$(params.gitrepositoryurl)"
        - name: revision
          value: "$(params.gitrevision)"
        - name: deleteExisting
          value: "true"
    - name: detect-changes
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source-workspace
      taskRef:
        name: detect-changes
      params:
        - name: gitrevision
          value: "$(params.gitrevision)"
    - name: buildpacks
      runAfter:
        - detect-changes
      when:
        - input: "$(tasks.detect-changes.results.should-build)"
          operator: in
          values: ["true"]
      taskRef:
        name: buildpacks-phases
      workspaces:
        - name: source
          workspace: source-workspace
      params:
        - name: APP_IMAGE
          value: "$(tasks.detect-changes.results.image)"
        - name: SOURCE_SUBPATH
          value: "$(tasks.detect-changes.results.source-subpath)"
        - name: CNB_BUILDER_IMAGE
          value: "$(tasks.detect-changes.results.builder)"
    - name: patch-deployment
      runAfter:
        - buildpacks
      when:
        - input: "$(params.action)"
          operator: in
          values: ["deploy"]
        - input: "$(tasks.detect-changes.results.should-build)"
          operator: in
          values: ["true"]
      taskRef:
        name: patch-deployment
      workspaces:
        - name: source
          workspace: source-workspace
      params:
        - name: DEPLOYMENT_NAME
          value: "$(tasks.detect-changes.results.component-name)"
        - name: IMAGE_NAME
          value: "$(tasks.detect-changes.results.image)"
        - name: TAG
          value: "$(params.gitrevision)"
