apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - sealed-gh-auth-secret.yaml
  - sealed-gh-webhook-secret.yaml
  - sealed-ghcr-secret.yaml
  # - shared-cache-pvc.yaml
  - triggers-webhook-service.yaml
