apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-service-account
secrets:
  - name: ghcr-creds
  - name: github-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-role
rules:
  - apiGroups: ["tekton.dev"]
    resources:
      - pipelineruns
      - pipelines
      - tasks
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      - eventlisteners
      - triggerbindings
      - triggers
      - clustertriggerbindings
      - clusterinterceptors
    verbs:
      - get
      - list
      - watch
      - update
      - patch  
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - patch
      - update
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
subjects:
  - kind: ServiceAccount
    name: pipeline-service-account
roleRef:
  kind: Role
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io