# Secret Documentation:
# - Why it is needed: Used by the git-clone task in the pipeline to authenticate with GitHub to clone private repositories.
# - Expiration date: 30 days
# - How to renew:
#   1. Generate a new Personal Access Token (PAT) with "repo" scope on GitHub.
#   2. Re-create and seal the secret locally:
#      kubectl create secret generic github-auth --from-literal=username=<username> --from-literal=password=<PAT> --dry-run=client -o yaml | kubeseal --format=yaml > sealed-gh-auth-secret.yaml
#   3. Apply the updated sealed-gh-auth-secret.yaml to your cluster.
# - Where to renew (url): https://github.com/settings/tokens
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: github-auth
spec:
  encryptedData:
    password: AgBiYW1lsXIdhBBOFnmKAGXQiiECiGUgJiHoaoC6FRWyv+Ec7UaGQslmltOws8WQFVNIBcj+njqoDwKXcMXbWsWz4YkO+WwhFBFyPHVrhsEV3oeTp+1U1Oek4yjlJmpUvSMABfbtC5FJsLZO0lZtUuozjnrHYKTMrEN5Li6GVu9G9AAou87egNhkKi8n+MVlj1em0YNAS7r0BEipJi+oLyqT+QEvu6Dyw/KMpMtt2dtCvBP84qjEB6pIQ8h+jSqqxlL0SdrkMkJwmTXFqsAoBtg3EqQTzDSDzcTTT4dN74IE0zfyDhrilIDrzwVXOj/y3oyQEfXvnP+/Ai1bmPLZYWE3wWItxN0tQPF1FXJ08z9r5R7NwduyYl6RBGLOOqDmgt5ijF0SVY/ILygTETZPRFycqOpySy57ELBUrUgNTxSqLrlZTUUlmqCutOySbnYvVtZ5n4HmyaRccaCyOkxG+lkYWlOgzCtUkd2VBNdTvuXNwj9bJfDLqaCRWqb79dmupR4f7C6P31pdv2SQSAWV6I/xLYAwCy0uVC530T/MVmyyZxHMmrNre5t8ih0Z6gsudniOhBLvVpkCty/ZTFnuQj+ztRHnfgWKjcYlw3dYtB5N/X7TQLjTszdGutGu5BFuQdeHVc3x+g7Ol1A//WsTUODIG7eufLiSUOLrpfAZxHR7L8LYtj3YZ4ieC7a+5Swncl6BSn5JH8kjBS+D+MlHJm6wgINM54nwJkixndl43p+qJp7SJ0bBtsra
    username: AgDF3W9TvbZ2GGzAbvb7MpZ/XifiwK4Rq4CfgUWy0aebcsYMo80audZs7myXzFmU/X52k02AYHqF9zNwv7CIR7xWtZyEULC66E/dD9vprnnEpJjvXDnO9p76UV8Oq7wDj7n5QJraGTfxbIf2vkj01W3937eLS7SATcWJH3h8a+OmHHeJDEe//XOrijlI9Ubab+kcDOOM4ZpqUBlhvwfff+wFwa7IiOdFGg0t+B0f5PwBjq208B5NXVjTTLTVgGhD8rabGLCGhNVhurdzVq/ZhNgj4/YFC3c8tj7FriT/2ftINAKkH/WuvTSOBKX9YqmWc3qG1GzHEkX/9uY/BaTYBQqLgekrlx3DWjfXRslTiXiEnt6EBDaPZxSYSdyiwNzPZ0mafFiP1VKXkEnXzM3qWiDiJhT3Mybdr7chLrgZlzf3HpfX5jFRjlKYqFRj1V22LypriWlDPQMcY0EtOH8uF7pEbysOKeHvBUnVtfPTbfx2BM1Q85T27COInazkLKMb5cIAHtpMyepgAyzYKdwGv2vBElx5qsZxJrHW5CCyfzvSRr4m4+bXYybWslDZ8JC8LK/icOWlPIVzcji5v3a8iZcC39VvDWo0JxUldsnWJcd18DAmPulKKSFMVo80yz4wsFQO1t3Lkysk8NBuXm5ucHJl2bb/o3pp7L8r3kkqURWqRhVeUeOuVKekglIUeYQz0ySWg6tW/xaS/1cN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      name: github-auth
