# Secret Documentation:
# - Why it is needed: Used by the container build tools (e.g., Cloud Native Buildpacks) to authenticate with GitHub Container Registry (GHCR) to push/pull container images.
# - Expiration date: 30 days
# - How to renew:
#   1. Generate a new Personal Access Token (PAT) on GitHub with "write:packages" and "read:packages" scopes.
#   2. Re-create and seal the docker-registry secret locally:
#      kubectl create secret docker-registry ghcr-creds --docker-server=ghcr.io --docker-username=<username> --docker-password=<PAT> --dry-run=client -o yaml | kubeseal --format=yaml > sealed-ghcr-secret.yaml
#   3. Apply the updated sealed-ghcr-secret.yaml to your cluster.
# - Where to renew (url): https://github.com/settings/tokens
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ghcr-creds
spec:
  encryptedData:
    .dockerconfigjson: AgB78sC6VUenLXq+WxMmQoVI1I9jobhM/+yvV0/Z9BGrF22oYIP5ws54CflsiayKev5LDXJQarCR1eYFRQTPK5J+aJOYfBUC2ATqaWDQzwjNzFvBbPdSlIsV2gM3mAxKfIfmcB5JLRwYJ06W6sCuxdy89tWribjyWWuTvnoWVzJJy7cMUPcRRb8cbrpg9Y7qmMrdDDvmMuezOWl2zGUCARHsK0hTyfi4nscOiJCNZgWkS07s0CpZtR2/ok/ONLs2lH3CeRj2BI53IxQ4CMDo9FTd3G3NoOQg46i2zpJzzjbDalSEE/ZqjeOaF9758MYbIvQeSQ1HcryeOiwZaIo5dYO8G/weEjbQpH5CMShSj0VP63ZkEpLpK6Twg09wYcfATZ2lLDHKbWoRGeOxk7ANZ7Uewg/7NUcdZbLNkjzUR9DshIzbnjT0WbLYcuiQQiHSIjUWHydcyZ98bRVBsHW4jkjWPHSgYWtjKVP9wm3DdGSK2CzNCH4ziW+j+1xBx449LZ/oVeujnkp2AvIoMU/g6CufIxTTqg6VI3Za64Ux7p69o1WhJOkVzNShz1CV2gNxtzdQIYkO8Nf7bh/9RBz+lCDDbnXu0ihXYk+nOJChgVV1YRlquUB8OqSKnDCwn3tkSdyuLoTetu3o6bu0a/brESanr1/jm3N+HU/v1gZZkY/g4DYXJsxyahUon0KzJKSEB6f5DnPb+MrW8fj6c7/lR/4h3OxB+5a2wyUvXV7smUQUlidc6gNEB0/MvcSvhXX4pSPBwbM410WR4Lv52Z+1wMhIsSuRBh9TL5qdONzBehMYCjn8l92l1nRpzUwQzh6uBsjTewiyZ4HdBeq5ij1vclFn2THkNzk2dWplBGXVteOnPfFJEVEEmm/+G9Ps/jdAA5fLvMZucUqD7CIcEfigK45xCNsJbLhYoLkVKOs+dFKNYqsGERrQDADlsVmH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ghcr-creds
    type: kubernetes.io/dockerconfigjson
