apiVersion: v1
kind: Service
metadata:
  name: gh-listener-webhook
spec:
  type: ExternalName
  externalName: el-gh-event-listener
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
