---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: github-webhook-secret
  namespace: default
spec:
  encryptedData:
    token: AgC3PXavPAh+yBQX5K19IwUuJ5cy+wZU576QPUakqNcsjKwdpcg5TzeQ9mp+rX8k/Pa6zLh3e0CIg/r7frHYCLcz2KVj+glA8wCBhfATkttiGm9i07lclLNjowzZBHEc7vlh3jcHXIqDE9JELb65uOSri/wNZnfongWpgmDShYhi1u9XocKth6MogEk+GC0uUCAdT+xZzg8BXbCb/Kv6EsmAPrWoDOocjjl1qdsycpOzCP+dyX8oTLi//tNWCeqs79lVpM9bSKJdCZcP8m5ZUvPVAgm929CTTU7eT5/SC3O5tMZm/5svvflU9VRjOQmAGKv8OPWZpYkjFlfrU3tFIA3JsrK7z/aj+TS0A51PAKE0kRtdd0zZhIdYmuRkFqei3YGGHcyGHEc6C38udEm+pzX3m0rEG+VJy+VDxmNgFvxznYRxywe7R0tvT39uzHdPjOqJtXe8SWebAmWoW1Zp06vCfeITJ7B2HreaEtyHXUOhLbgKhr5dZBuPN1p090lqcuXBULYHKhD6aHEg2Zw1ZksehTvVgUTNMYuWp03VKPOv3ose7QdeqPm9EFLQGl8gpu2zFm4JoDAmOGNWJ+sVbZc6MQGYE96JlNkqSo0PlyCuYZF4vttyYOuO6K58IPater/Sd+lRBkpsZPDg/APhjIwcHFl75QA5SY3htlpPdWsZVB3UFB64tQLs7bnvOyg10UWZzKnzJdYCSiTIv1QwROsdHWZDTsY3hbuYHVnnjl4+/AobCw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: github-webhook-secret
      namespace: default
    type: Opaque
