apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: component-dispatch-binding
  namespace: saritasa-test
spec:
  params:
    - name: component
      value: $(body.component)
    - name: component-clean
      value: $(extensions.component_clean)
    - name: git-revision
      value: $(body.git-revision)
    - name: git-repository-url
      value: $(body.git-repository-url)
    - name: registry-path
      value: $(body.registry-path)
    - name: action
      value: $(body.action)
    - name: max-concurrency
      value: $(body.max-concurrency)
    - name: namespace
      value: $(body.namespace)
    - name: container-name
      value: $(body.container-name)
    - name: clone-depth
      value: $(body.clone-depth)
    - name: delete-existing
      value: $(body.delete-existing)
    - name: parent-pipelinerun
      value: $(body.parent-pipelinerun)
    - name: timeout
      value: $(body.timeout)
    - name: deployment-timeout
      value: $(body.deployment-timeout)
    - name: size
      value: $(body.size)

