apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gh-event-listener
  namespace: saritasa-test
spec:
  serviceAccountName: pipeline-service-account
  triggers:
    - name: merge-main-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: "github-webhook-secret"
                secretKey: "token"
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/main'"
      bindings:
        - ref: github-merge-binding
      template:
        ref: trigger-template