---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-merge-binding
spec:
  params:
    - name: git-revision
      value: $(body.after)
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: changed-modules
      value: $(extensions.changed_modules)
    - name: find-child-timeout
      value: "30"
    