apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: git-revision
      description: The git revision/sha to build
    - name: git-repository-url
      description: The git repository URL
    - name: action
      description: The action to perform (build or deploy)
    - name: registry-path
      description: The target docker registry path
    - name: max-concurrency
      description: Maximum number of concurrent PipelineRuns allowed in the namespace.
    - name: namespace
      description: The namespace to check active PipelineRuns in.
    - name: container-name
      description: The container name in the Deployment to patch.
    - name: clone-depth
      description: The depth of the git clone.
    - name: delete-existing
      description: Clean out the contents of the repo's destination directory if it already exists before cloning.
    - name: changed-modules
      description: The list of changed modules to build.
    - name: timeout
      description: The timeout for the component pipelines
    - name: deployment-timeout
      description: The timeout for the deployment rollout check
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: orchestrator-pipelinerun-
      spec:
        serviceAccountName: pipeline-service-account
        pipelineRef:
          name: orchestrator-pipeline
        podTemplate:
          nodeSelector:
            node: hp
        params:
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: git-repository-url
            value: $(tt.params.git-repository-url)
          - name: action
            value: $(tt.params.action)
          - name: registry-path
            value: $(tt.params.registry-path)
          - name: max-concurrency
            value: $(tt.params.max-concurrency)
          - name: namespace
            value: $(tt.params.namespace)
          - name: container-name
            value: $(tt.params.container-name)
          - name: clone-depth
            value: $(tt.params.clone-depth)
          - name: delete-existing
            value: $(tt.params.delete-existing)
          - name: changed-modules
            value: $(tt.params.changed-modules)
          - name: timeout
            value: $(tt.params.timeout)
          - name: deployment-timeout
            value: $(tt.params.deployment-timeout)


